import os
import re

# Use these commands to get the nuisance names
#sed -n 's/\(^[^ ].*[shape|lnN]\).*/\1/p' vhbb_VH_7p8TeV.txt > ! temp
#sed -i 's/\(.*\w\) .*[shape|lnN]/("\1",""),/' temp
#cat temp

nuisances = [
("FULL","FULL"),
("CMS_vhbb_EWK_Zll","theoryMC"),
("CMS_vhbb_LHE_weights_pdf_TT","theoryMC"),
("CMS_vhbb_LHE_weights_pdf_VVHF","theoryMC"),
("CMS_vhbb_LHE_weights_pdf_VVLF","theoryMC"),
("CMS_vhbb_LHE_weights_pdf_WH","theorySIG"),
("CMS_vhbb_LHE_weights_pdf_Wj0b","theoryMC"),
("CMS_vhbb_LHE_weights_pdf_Wj1b","theoryMC"),
("CMS_vhbb_LHE_weights_pdf_Wj2b","theoryMC"),
("CMS_vhbb_LHE_weights_pdf_ZH","theorySIG"),
("CMS_vhbb_LHE_weights_pdf_Zj0b","theoryMC"),
("CMS_vhbb_LHE_weights_pdf_Zj1b","theoryMC"),
("CMS_vhbb_LHE_weights_pdf_Zj2b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muF_QCD","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muF_TT","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muF_VVHF","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muF_VVLF","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muF_WH","theorySIG"),
("CMS_vhbb_LHE_weights_scale_muF_Wj0b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muF_Wj1b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muF_Wj2b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muF_ZH","theorySIG"),
("CMS_vhbb_LHE_weights_scale_muF_Zj0b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muF_Zj1b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muF_Zj2b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muF_ggZH","theorySIG"),
("CMS_vhbb_LHE_weights_scale_muR_QCD","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muR_TT","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muR_VVHF","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muR_VVLF","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muR_WH","theorySIG"),
("CMS_vhbb_LHE_weights_scale_muR_Wj0b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muR_Wj1b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muR_Wj2b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muR_ZH","theorySIG"),
("CMS_vhbb_LHE_weights_scale_muR_Zj0b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muR_Zj1b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muR_Zj2b","theoryMC"),
("CMS_vhbb_LHE_weights_scale_muR_ggZH","theorySIG"),
("CMS_vhbb_ST","SFsmc"),
("CMS_vhbb_VV","SFsmc"),
("CMS_vhbb_bTagWeightHFStats1_pt0_eta1","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt0_eta2","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt0_eta3","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt1_eta1","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt1_eta2","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt1_eta3","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt2_eta1","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt2_eta2","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt2_eta3","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt3_eta1","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt3_eta2","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt3_eta3","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt4_eta1","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt4_eta2","mistag"),
("CMS_vhbb_bTagWeightHFStats1_pt4_eta3","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt0_eta1","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt0_eta2","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt0_eta3","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt1_eta1","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt1_eta2","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt1_eta3","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt2_eta1","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt2_eta2","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt2_eta3","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt3_eta1","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt3_eta2","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt3_eta3","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt4_eta1","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt4_eta2","mistag"),
("CMS_vhbb_bTagWeightHFStats2_pt4_eta3","mistag"),
("CMS_vhbb_bTagWeightHF_pt0_eta1","mistag"),
("CMS_vhbb_bTagWeightHF_pt0_eta2","mistag"),
("CMS_vhbb_bTagWeightHF_pt0_eta3","mistag"),
("CMS_vhbb_bTagWeightHF_pt1_eta1","mistag"),
("CMS_vhbb_bTagWeightHF_pt1_eta2","mistag"),
("CMS_vhbb_bTagWeightHF_pt1_eta3","mistag"),
("CMS_vhbb_bTagWeightHF_pt2_eta1","mistag"),
("CMS_vhbb_bTagWeightHF_pt2_eta2","mistag"),
("CMS_vhbb_bTagWeightHF_pt2_eta3","mistag"),
("CMS_vhbb_bTagWeightHF_pt3_eta1","mistag"),
("CMS_vhbb_bTagWeightHF_pt3_eta2","mistag"),
("CMS_vhbb_bTagWeightHF_pt3_eta3","mistag"),
("CMS_vhbb_bTagWeightHF_pt4_eta1","mistag"),
("CMS_vhbb_bTagWeightHF_pt4_eta2","mistag"),
("CMS_vhbb_bTagWeightHF_pt4_eta3","mistag"),
("CMS_vhbb_bTagWeightJES_pt0_eta1","btag"),
("CMS_vhbb_bTagWeightJES_pt0_eta2","btag"),
("CMS_vhbb_bTagWeightJES_pt0_eta3","btag"),
("CMS_vhbb_bTagWeightJES_pt1_eta1","btag"),
("CMS_vhbb_bTagWeightJES_pt1_eta2","btag"),
("CMS_vhbb_bTagWeightJES_pt1_eta3","btag"),
("CMS_vhbb_bTagWeightJES_pt2_eta1","btag"),
("CMS_vhbb_bTagWeightJES_pt2_eta2","btag"),
("CMS_vhbb_bTagWeightJES_pt2_eta3","btag"),
("CMS_vhbb_bTagWeightJES_pt3_eta1","btag"),
("CMS_vhbb_bTagWeightJES_pt3_eta2","btag"),
("CMS_vhbb_bTagWeightJES_pt3_eta3","btag"),
("CMS_vhbb_bTagWeightJES_pt4_eta1","btag"),
("CMS_vhbb_bTagWeightJES_pt4_eta2","btag"),
("CMS_vhbb_bTagWeightJES_pt4_eta3","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt0_eta1","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt0_eta2","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt0_eta3","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt1_eta1","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt1_eta2","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt1_eta3","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt2_eta1","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt2_eta2","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt2_eta3","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt3_eta1","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt3_eta2","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt3_eta3","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt4_eta1","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt4_eta2","btag"),
("CMS_vhbb_bTagWeightLFStats1_pt4_eta3","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt0_eta1","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt0_eta2","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt0_eta3","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt1_eta1","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt1_eta2","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt1_eta3","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt2_eta1","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt2_eta2","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt2_eta3","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt3_eta1","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt3_eta2","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt3_eta3","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt4_eta1","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt4_eta2","btag"),
("CMS_vhbb_bTagWeightLFStats2_pt4_eta3","btag"),
("CMS_vhbb_bTagWeightLF_pt0_eta1","btag"),
("CMS_vhbb_bTagWeightLF_pt0_eta2","btag"),
("CMS_vhbb_bTagWeightLF_pt0_eta3","btag"),
("CMS_vhbb_bTagWeightLF_pt1_eta1","btag"),
("CMS_vhbb_bTagWeightLF_pt1_eta2","btag"),
("CMS_vhbb_bTagWeightLF_pt1_eta3","btag"),
("CMS_vhbb_bTagWeightLF_pt2_eta1","btag"),
("CMS_vhbb_bTagWeightLF_pt2_eta2","btag"),
("CMS_vhbb_bTagWeightLF_pt2_eta3","btag"),
("CMS_vhbb_bTagWeightLF_pt3_eta1","btag"),
("CMS_vhbb_bTagWeightLF_pt3_eta2","btag"),
("CMS_vhbb_bTagWeightLF_pt3_eta3","btag"),
("CMS_vhbb_bTagWeightLF_pt4_eta1","btag"),
("CMS_vhbb_bTagWeightLF_pt4_eta2","btag"),
("CMS_vhbb_bTagWeightLF_pt4_eta3","btag"),
("CMS_vhbb_bTagWeightcErr1_pt0_eta1","btag"),
("CMS_vhbb_bTagWeightcErr1_pt0_eta2","btag"),
("CMS_vhbb_bTagWeightcErr1_pt0_eta3","btag"),
("CMS_vhbb_bTagWeightcErr1_pt1_eta1","btag"),
("CMS_vhbb_bTagWeightcErr1_pt1_eta2","btag"),
("CMS_vhbb_bTagWeightcErr1_pt1_eta3","btag"),
("CMS_vhbb_bTagWeightcErr1_pt2_eta1","btag"),
("CMS_vhbb_bTagWeightcErr1_pt2_eta2","btag"),
("CMS_vhbb_bTagWeightcErr1_pt2_eta3","btag"),
("CMS_vhbb_bTagWeightcErr1_pt3_eta1","btag"),
("CMS_vhbb_bTagWeightcErr1_pt3_eta2","btag"),
("CMS_vhbb_bTagWeightcErr1_pt3_eta3","btag"),
("CMS_vhbb_bTagWeightcErr1_pt4_eta1","btag"),
("CMS_vhbb_bTagWeightcErr1_pt4_eta2","btag"),
("CMS_vhbb_bTagWeightcErr1_pt4_eta3","btag"),
("CMS_vhbb_bTagWeightcErr2_pt0_eta1","btag"),
("CMS_vhbb_bTagWeightcErr2_pt0_eta2","btag"),
("CMS_vhbb_bTagWeightcErr2_pt0_eta3","btag"),
("CMS_vhbb_bTagWeightcErr2_pt1_eta1","btag"),
("CMS_vhbb_bTagWeightcErr2_pt1_eta2","btag"),
("CMS_vhbb_bTagWeightcErr2_pt1_eta3","btag"),
("CMS_vhbb_bTagWeightcErr2_pt2_eta1","btag"),
("CMS_vhbb_bTagWeightcErr2_pt2_eta2","btag"),
("CMS_vhbb_bTagWeightcErr2_pt2_eta3","btag"),
("CMS_vhbb_bTagWeightcErr2_pt3_eta1","btag"),
("CMS_vhbb_bTagWeightcErr2_pt3_eta2","btag"),
("CMS_vhbb_bTagWeightcErr2_pt3_eta3","btag"),
("CMS_vhbb_bTagWeightcErr2_pt4_eta1","btag"),
("CMS_vhbb_bTagWeightcErr2_pt4_eta2","btag"),
("CMS_vhbb_bTagWeightcErr2_pt4_eta3","btag"),
("CMS_vhbb_boost_EWK_13TeV","theorySIG"),
("CMS_vhbb_boost_QCD_13TeV","theorySIG"),
("CMS_vhbb_eff_e_MVAID_Zll_13TeV","effl"),
("CMS_vhbb_eff_e_Wln_13TeV","effl"),
("CMS_vhbb_eff_e_tracker_Zll_13TeV","effl"),
("CMS_vhbb_eff_e_trigger_Zll_13TeV","effl"),
("CMS_vhbb_eff_m_ISO_Zll_13TeV","effl"),
("CMS_vhbb_eff_m_MVAID_Zll_13TeV","effl"),
("CMS_vhbb_eff_m_Wln_13TeV","effl"),
("CMS_vhbb_eff_m_tracker_Zll_13TeV","effl"),
("CMS_vhbb_eff_m_trigger_Zll_13TeV","effl"),
("CMS_vhbb_ptwweights_tt","model"),
("CMS_vhbb_ptwweights_whf","model"),
("CMS_vhbb_ptwweights_wlf","model"),
("CMS_vhbb_puWeight","lumi"),
("CMS_vhbb_res_j_13TeV","res"),
("CMS_vhbb_scale_j_AbsoluteMPFBias_13TeV","jec"),
("CMS_vhbb_scale_j_AbsoluteScale_13TeV","jec"),
("CMS_vhbb_scale_j_AbsoluteStat_13TeV","jec"),
("CMS_vhbb_scale_j_FlavorQCD_13TeV","jec"),
("CMS_vhbb_scale_j_Fragmentation_13TeV","jec"),
("CMS_vhbb_scale_j_PileUpDataMC_13TeV","jec"),
("CMS_vhbb_scale_j_PileUpPtBB_13TeV","jec"),
("CMS_vhbb_scale_j_PileUpPtEC1_13TeV","jec"),
("CMS_vhbb_scale_j_PileUpPtEC2_13TeV","jec"),
("CMS_vhbb_scale_j_PileUpPtRef_13TeV","jec"),
("CMS_vhbb_scale_j_RelativeFSR_13TeV","jec"),
("CMS_vhbb_scale_j_RelativeJEREC1_13TeV","jec"),
("CMS_vhbb_scale_j_RelativePtBB_13TeV","jec"),
("#CMS_vhbb_scale_j_RelativePtEC1_13TeV","jec"),
("CMS_vhbb_scale_j_RelativePtEC2_13TeV","jec"),
("CMS_vhbb_scale_j_RelativeStatEC_13TeV","jec"),
("CMS_vhbb_scale_j_RelativeStatFSR_13TeV","jec"),
("CMS_vhbb_scale_j_SinglePionECAL_13TeV","jec"),
("CMS_vhbb_scale_j_SinglePionHCAL_13TeV","jec"),
("CMS_vhbb_scale_j_TimePtEta_13TeV","jec"),
("CMS_vhbb_statTT_WenHighPt_bin1_13TeV","stat"),
("CMS_vhbb_statTT_WenHighPt_bin2_13TeV","stat"),
("CMS_vhbb_statTT_WenHighPt_bin3_13TeV","stat"),
("CMS_vhbb_statTT_WenHighPt_bin4_13TeV","stat"),
("CMS_vhbb_statTT_WenHighPt_bin5_13TeV","stat"),
("CMS_vhbb_statTT_WenHighPt_bin6_13TeV","stat"),
("CMS_vhbb_statTT_WenHighPt_bin7_13TeV","stat"),
("CMS_vhbb_statTT_WmnHighPt_bin1_13TeV","stat"),
("CMS_vhbb_statTT_WmnHighPt_bin2_13TeV","stat"),
("CMS_vhbb_statTT_WmnHighPt_bin3_13TeV","stat"),
("CMS_vhbb_statTT_WmnHighPt_bin4_13TeV","stat"),
("CMS_vhbb_statTT_WmnHighPt_bin5_13TeV","stat"),
("CMS_vhbb_statTT_WmnHighPt_bin6_13TeV","stat"),
("CMS_vhbb_statTT_WmnHighPt_bin7_13TeV","stat"),
("CMS_vhbb_statTT_WmnHighPt_bin8_13TeV","stat"),
("CMS_vhbb_statTT_WmnHighPt_bin9_13TeV","stat"),
("CMS_vhbb_statVVHF_WenHighPt_bin10_13TeV","stat"),
("CMS_vhbb_statVVHF_WmnHighPt_bin10_13TeV","stat"),
("CMS_vhbb_statVVHF_WmnHighPt_bin7_13TeV","stat"),
("CMS_vhbb_statVVHF_WmnHighPt_bin8_13TeV","stat"),
("CMS_vhbb_statVVLF_WenHighPt_bin4_13TeV","stat"),
("CMS_vhbb_statVVLF_WenHighPt_bin6_13TeV","stat"),
("CMS_vhbb_statVVLF_WmnHighPt_bin1_13TeV","stat"),
("CMS_vhbb_statVVLF_WmnHighPt_bin3_13TeV","stat"),
("CMS_vhbb_statVVLF_WmnHighPt_bin4_13TeV","stat"),
("CMS_vhbb_statVVLF_WmnHighPt_bin5_13TeV","stat"),
("CMS_vhbb_statVVLF_WmnHighPt_bin9_13TeV","stat"),
("CMS_vhbb_statWj0b_WenHighPt_bin10_13TeV","stat"),
("CMS_vhbb_statWj0b_WenHighPt_bin1_13TeV","stat"),
("CMS_vhbb_statWj0b_WenHighPt_bin2_13TeV","stat"),
("CMS_vhbb_statWj0b_WenHighPt_bin3_13TeV","stat"),
("CMS_vhbb_statWj0b_WenHighPt_bin4_13TeV","stat"),
("CMS_vhbb_statWj0b_WenHighPt_bin5_13TeV","stat"),
("CMS_vhbb_statWj0b_WenHighPt_bin6_13TeV","stat"),
("CMS_vhbb_statWj0b_WenHighPt_bin9_13TeV","stat"),
("CMS_vhbb_statWj0b_WmnHighPt_bin10_13TeV","stat"),
("CMS_vhbb_statWj0b_WmnHighPt_bin1_13TeV","stat"),
("CMS_vhbb_statWj0b_WmnHighPt_bin2_13TeV","stat"),
("CMS_vhbb_statWj0b_WmnHighPt_bin3_13TeV","stat"),
("CMS_vhbb_statWj0b_WmnHighPt_bin4_13TeV","stat"),
("CMS_vhbb_statWj0b_WmnHighPt_bin5_13TeV","stat"),
("CMS_vhbb_statWj0b_WmnHighPt_bin6_13TeV","stat"),
("CMS_vhbb_statWj0b_WmnHighPt_bin7_13TeV","stat"),
("CMS_vhbb_statWj0b_WmnHighPt_bin8_13TeV","stat"),
("CMS_vhbb_statWj0b_WmnHighPt_bin9_13TeV","stat"),
("CMS_vhbb_statWj1b_WenHighPt_bin1_13TeV","stat"),
("CMS_vhbb_statWj1b_WmnHighPt_bin2_13TeV","stat"),
("CMS_vhbb_statWj2b_WmnHighPt_bin1_13TeV","stat"),
("CMS_vhbb_statZH_hbb_WenHighPt_bin10_13TeV","stat"),
("CMS_vhbb_statZH_hbb_WenHighPt_bin9_13TeV","stat"),
("CMS_vhbb_statZH_hbb_WmnHighPt_bin10_13TeV","stat"),
("CMS_vhbb_statZH_hbb_WmnHighPt_bin9_13TeV","stat"),
("CMS_vhbb_statZj0b_WenHighPt_bin1_13TeV","stat"),
("CMS_vhbb_statZj0b_WenHighPt_bin5_13TeV","stat"),
("CMS_vhbb_statZj0b_WmnHighPt_bin3_13TeV","stat"),
("CMS_vhbb_statZj1b_WenHighPt_bin1_13TeV","stat"),
("CMS_vhbb_statZj1b_WenHighPt_bin2_13TeV","stat"),
("CMS_vhbb_statZj1b_WenHighPt_bin3_13TeV","stat"),
("CMS_vhbb_statZj1b_WenHighPt_bin9_13TeV","stat"),
("CMS_vhbb_statZj1b_WmnHighPt_bin1_13TeV","stat"),
("CMS_vhbb_statZj1b_WmnHighPt_bin3_13TeV","stat"),
("CMS_vhbb_statZj2b_WenHighPt_bin1_13TeV","stat"),
("CMS_vhbb_statZj2b_WenHighPt_bin2_13TeV","stat"),
("CMS_vhbb_statZj2b_WenHighPt_bin3_13TeV","stat"),
("CMS_vhbb_statZj2b_WenHighPt_bin5_13TeV","stat"),
("CMS_vhbb_statZj2b_WmnHighPt_bin1_13TeV","stat"),
("CMS_vhbb_statZj2b_WmnHighPt_bin2_13TeV","stat"),
("CMS_vhbb_statZj2b_WmnHighPt_bin3_13TeV","stat"),
("CMS_vhbb_stats_Top_WenHighPt_bin3_13TeV","stat"),
("CMS_vhbb_stats_Top_WenHighPt_bin4_13TeV","stat"),
("CMS_vhbb_stats_Top_WenHighPt_bin5_13TeV","stat"),
("CMS_vhbb_stats_Top_WenHighPt_bin7_13TeV","stat"),
("CMS_vhbb_stats_Top_WenHighPt_bin8_13TeV","stat"),
("CMS_vhbb_stats_Top_WenHighPt_bin9_13TeV","stat"),
("CMS_vhbb_stats_Top_WmnHighPt_bin1_13TeV","stat"),
("CMS_vhbb_stats_Top_WmnHighPt_bin2_13TeV","stat"),
("CMS_vhbb_stats_Top_WmnHighPt_bin3_13TeV","stat"),
("CMS_vhbb_stats_Top_WmnHighPt_bin4_13TeV","stat"),
("CMS_vhbb_stats_Top_WmnHighPt_bin7_13TeV","stat"),
("CMS_vhbb_stats_Top_WmnHighPt_bin8_13TeV","stat"),
("CMS_vhbb_stats_bin10_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin10_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin10_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin11_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin11_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin11_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin12_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin12_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin13_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin13_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin14_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin14_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin14_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin15_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin15_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin15_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin17_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin17_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin18_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin18_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin19_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin19_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin1_TT_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_TT_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_TT_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_TT_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_VVLF_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_VVLF_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_VVLF_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_VVLF_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin1_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin1_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin1_Zj0b_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_Zj0b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_Zj0b_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_Zj0b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_Zj1b_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_Zj1b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_Zj1b_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_Zj1b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_Zj2b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_Zj2b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_s_Top_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_s_Top_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_s_Top_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin1_s_Top_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin20_VVLF_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin20_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin20_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin21_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin22_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin22_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin23_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin24_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin24_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin24_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin25_VVLF_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin25_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin26_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin26_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin27_VVLF_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin27_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin27_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin28_VVLF_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin28_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin28_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin29_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin2_TT_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_TT_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_TT_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_TT_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_VVLF_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin2_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin2_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin2_Zj0b_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_Zj0b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_Zj0b_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_Zj0b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_Zj1b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_Zj1b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_Zj2b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_Zj2b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_s_Top_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_s_Top_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_s_Top_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin2_s_Top_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin31_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin31_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin31_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin32_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin32_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin32_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin33_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin35_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin35_Zj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin3_TT_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_TT_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_TT_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_TT_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin3_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin3_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin3_Zj0b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_Zj0b_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_Zj0b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_Zj1b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_Zj1b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_Zj2b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_Zj2b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_s_Top_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_s_Top_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_s_Top_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin3_s_Top_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin4_TT_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin4_TT_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin4_TT_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin4_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin4_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin4_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin4_Zj0b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin4_Zj0b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin4_Zj1b_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin4_Zj1b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin4_Zj1b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin4_Zj2b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin4_Zj2b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin4_s_Top_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin4_s_Top_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_TT_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_TT_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_TT_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_TT_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_VVLF_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin5_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin5_Zj0b_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_Zj0b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_Zj0b_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_Zj0b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_Zj1b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_Zj1b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_Zj2b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_Zj2b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_s_Top_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin5_s_Top_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin6_TT_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin6_TT_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin6_VVHF_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin6_VVLF_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin6_VVLF_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin6_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin6_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin6_Zj0b_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin6_Zj0b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin6_Zj0b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin6_Zj1b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin6_Zj1b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin6_Zj2b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin6_Zj2b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_TT_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_TT_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_VVHF_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_VVHF_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin7_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin7_Zj0b_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_Zj0b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_Zj0b_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_Zj0b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_Zj1b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_Zj1b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_Zj2b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_Zj2b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin7_s_Top_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_TT_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_TT_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_VVHF_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_VVLF_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_VVLF_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_VVLF_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_VVLF_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin8_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin8_Zj0b_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_Zj0b_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_Zj0b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_Zj1b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_Zj1b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin8_Zj2b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin9_TT_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin9_VVHF_ZeeHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin9_VVHF_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin9_VVLF_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin9_VVLF_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin9_Wj0b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin9_Wj1b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin9_Wj2b_Znn_13TeV_Signal","stat"),
("CMS_vhbb_stats_bin9_Zj0b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin9_Zj0b_ZuuHighPt_13TeV","stat"),
("CMS_vhbb_stats_bin9_Zj0b_ZuuLowPt_13TeV","stat"),
("CMS_vhbb_stats_bin9_Zj1b_ZeeLowPt_13TeV","stat"),
("CMS_vhbb_trigger_MET_13TeV","met"),
("QCDscale_VH","theorySIG"),
("QCDscale_VH_ggZHacceptance_highPt","theorySIG"),
("QCDscale_VH_ggZHacceptance_lowPt","theorySIG"),
("QCDscale_VV","theoryMC"),
("QCDscale_ttbar","theoryMC"),
("lumi_13TeV","lumi"),
("pdf_gg","theorySIG"),
("pdf_qqbar","theorySIG"),
("SF_Zj1b_norm_low_Zll  rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Zj1b_norm_high_Zll  rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_Zj1b_Znn   rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Zj0b_Znn   rateParam","SFsdata"),
("SF_Zj0b_norm_high_Zll  rateParam","SFsdata"),
("SF_TT_norm_high_Zll  rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Zj1b_norm_low_Zll  rateParam","SFsdata"),
("SF_TT_Wln     rateParam","SFsdata"),
("SF_TT_Znn     rateParam","SFsdata"),
("SF_Zj1b_Znn   rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_TT_Wln     rateParam","SFsdata"),
("SF_TT_norm_high_Zll  rateParam","SFsdata"),
("SF_TT_Wln     rateParam","SFsdata"),
("SF_TT_Wln     rateParam","SFsdata"),
("SF_Zj0b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj2b_Znn   rateParam","SFsdata"),
("SF_Zj0b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj2b_norm_low_Zll  rateParam","SFsdata"),
("SF_Zj2b_norm_high_Zll  rateParam","SFsdata"),
("SF_TT_Wln     rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_Zj1b_Znn   rateParam","SFsdata"),
("SF_TT_norm_high_Zll  rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_TT_norm_low_Zll  rateParam","SFsdata"),
("SF_Zj2b_norm_low_Zll  rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_Zj0b_norm_high_Zll  rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_Zj2b_norm_low_Zll  rateParam","SFsdata"),
("SF_Zj1b_norm_low_Zll  rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_TT_norm_low_Zll  rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_Zj1b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj1b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj0b_norm_low_Zll  rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_Zj1b_norm_low_Zll  rateParam","SFsdata"),
("SF_TT_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj0b_Znn   rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_Zj0b_norm_low_Zll  rateParam","SFsdata"),
("SF_Zj0b_norm_low_Zll  rateParam","SFsdata"),
("SF_Zj2b_norm_high_Zll  rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_Zj0b_Znn   rateParam","SFsdata"),
("SF_TT_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj0b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj2b_norm_high_Zll  rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_Zj1b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj0b_norm_low_Zll  rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_Zj0b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj0b_norm_low_Zll  rateParam","SFsdata"),
("SF_TT_norm_low_Zll  rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Zj0b_Znn   rateParam","SFsdata"),
("SF_TT_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj2b_norm_high_Zll  rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_Zj2b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj2b_norm_low_Zll  rateParam","SFsdata"),
("SF_TT_Wln     rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_Zj2b_Znn   rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_TT_Wln     rateParam","SFsdata"),
("SF_Zj1b_norm_low_Zll  rateParam","SFsdata"),
("SF_Zj2b_norm_low_Zll  rateParam","SFsdata"),
("SF_Zj1b_norm_low_Zll  rateParam","SFsdata"),
("SF_Zj2b_norm_low_Zll  rateParam","SFsdata"),
("SF_TT_norm_low_Zll  rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_Zj1b_norm_high_Zll  rateParam","SFsdata"),
("SF_TT_Znn     rateParam","SFsdata"),
("SF_Zj2b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj0b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj1b_norm_low_Zll  rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Zj2b_norm_low_Zll  rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_Zj2b_Znn   rateParam","SFsdata"),
("SF_TT_Znn     rateParam","SFsdata"),
("SF_TT_Wln     rateParam","SFsdata"),
("SF_TT_Wln     rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Zj2b_norm_low_Zll  rateParam","SFsdata"),
("SF_TT_norm_low_Zll  rateParam","SFsdata"),
("SF_Zj0b_norm_high_Zll  rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_Zj1b_norm_high_Zll  rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_Zj1b_norm_low_Zll  rateParam","SFsdata"),
("SF_Zj1b_Znn   rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_Zj2b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj2b_Znn   rateParam","SFsdata"),
("SF_TT_norm_low_Zll  rateParam","SFsdata"),
("SF_Zj1b_norm_high_Zll  rateParam","SFsdata"),
("SF_TT_norm_low_Zll  rateParam","SFsdata"),
("SF_TT_norm_high_Zll  rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_TT_Wln     rateParam","SFsdata"),
("SF_Zj2b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj1b_norm_high_Zll  rateParam","SFsdata"),
("SF_Zj0b_norm_low_Zll  rateParam","SFsdata"),
("SF_TT_Znn     rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Wj2b_Wln   rateParam","SFsdata"),
("SF_Wj0b_Wln   rateParam","SFsdata"),
("SF_Wj1b_Wln   rateParam","SFsdata"),
("SF_Zj0b_norm_low_Zll  rateParam","SFsdata"),
("SF_Zj0b_norm_low_Zll  rateParam","SFsdata"),
("SF_TT_norm_low_Zll  rateParam","SFsdata"),
("SF_TT_norm_high_Zll  rateParam","SFsdata"),

]

#orig = "vhbb_Znn_8TeV.txt"
#test = "test_8TeV.txt"
orig = "vhbb_2016_13TeV.txt"
test = "test_13TeV.txt"
#comm1 = "combine -M MaxLikelihoodFit -m 125 --robustFit=1 --stepSize=0.05 --rMin=-5 --rMax=5 -t -1 --expectSignal=1 "
comm2 = "combine -M ProfileLikelihood -m 125 --signif --pvalue -t -1 --expectSignal=1 "
#log1 = "syst_mu.log"
log2 = "syst_sig.log"
quantify1 = []
quantify2 = []

nuisances_1 = []
nuisances_2 = []
for n1, n2 in nuisances:
    if n2 in nuisances_2:
        nuisances_1[nuisances_2.index(n2)].append(n1)
    else:
        nuisances_1.append([n1])
        nuisances_2.append(n2)

for i in xrange(len(nuisances_1)):
    print nuisances_2[i]
    print nuisances_1[i]


for nui, nn in zip(nuisances_2, nuisances_1):
    os.system("cp " + orig + " " + test)
    os.system("sed -i 's/^kmax.*/kmax */' " + test)
    writeme = []
    with open(test,"r") as f:
        for line in f:
            for n in nn:
                line = line.replace(n, "#"+n)
            writeme.append(line)
    with open(test,"w") as f:
        f.write('\n'.join(writeme))
    
#    os.system(comm1 + test + " > %s" % log1)
    os.system(comm2 + test + " > %s" % log2)

 #   with open(log1) as f:
 #       for line in f:
 #           m = re.match("Best fit r: (.*)  (.*)/(.*)  \(68% CL\)", line)
 #           if m:
 #               sigma = (float(m.group(2)) * -1. + float(m.group(3))) / 2
 #               print nui, m.group(2), m.group(3), sigma 
 #               if not quantify1:
 #                   quantify1.append((nui, sigma, sigma/sigma))
 #               else:
 #                   quantify1.append(("NO "+nui, sigma, sigma/quantify1[0][1]))

    with open(log2) as f:
        for line in f:
            m = re.match("       \(Significance = (.*)\)", line)
            if m:
                signif = float(m.group(1))
                print nui, m.group(1)
                if not quantify2:
                    quantify2.append((nui, signif, signif/signif))
                else:
                    quantify2.append(("NO "+nui, signif, signif/quantify2[0][1]))

#print "metric: mu uncertainty"
#quantify1.sort(key=lambda tup: tup[2], reverse=True)
#for q in quantify1:
#    print "%-40s %.4f %.4f" % (q[0], q[1], q[2]*100.)

print "metric: significance"
quantify2.sort(key=lambda tup: tup[2], reverse=True)
for q in quantify2:
    print "%-40s %.4f %.4f" % (q[0], q[1], q[2]*100.)
